---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-endpoints
  namespace: pdns
subsets:
- addresses:
  - ip: 192.168.100.20
  - ip: 192.168.100.21
  - ip: 192.168.100.21
  ports:
  - port: 1
    protocol: TCP
---    
apiVersion: v1
kind: Service
metadata:
  name: glusterfs-endpoints
  namespace: pdns
spec:
  ports:
  - port: 1
