---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mariadb-pdns
    app.kubernetes.io/part-of: pdns
    app.kubernetes.io/component: mariadb
  name: mariadb-pdns
  namespace: pdns
spec:
  clusterIP: None
  ports:
  - name: tcp-mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app.kubernetes.io/name: mariadb-pdns
    app.kubernetes.io/part-of: pdns
    app.kubernetes.io/component: mariadb
  sessionAffinity: None
  type: ClusterIP
